### ISSUE TITLE
Couldn't Compile: fatal error: sys/uio.h: No such file or directory

### ISSUE THREAD

**Issue by SammDu** [abique/vst-bridge#17]
I was trying to compile it on a Ubuntu-gnome 64bit system, after "./configure" and "make", it prompted the following error:

    make[1]: Entering directory '/home/samm/Downloads/vst-bridge-master/host'
    wineg++ -m32 -D_GNU_SOURCE  -W -Wall -pipe -Wundef -Wshadow -Wpointer-arith -Wabi -std=c++11 -g host.cc -lpthread -lshell32 -lws2_32 -lX11 -o vst-bridge-host-32.exe
    host.cc:1:21: fatal error: sys/uio.h: No such file or directory
     #include <sys/uio.h>
                         ^
    compilation terminated.
    winegcc: g++ failed
    Makefile:8: recipe for target 'vst-bridge-host-32.exe' failed
    make[1]: *** [vst-bridge-host-32.exe] Error 2
    make[1]: Leaving directory '/home/samm/Downloads/vst-bridge-master/host'
    Makefile:2: recipe for target 'all' failed
    make: *** [all] Error 2
***
I've tried loading the **vstsdk2.4** folder with the [Official VST3 SDK](http://www.steinberg.net/nc/en/company/developer/) and the 2.4 version found [here](https://github.com/aardvarkk/soundfind/tree/master/vstsdk2.4)   
Nothing worked...plz help!! Thanks in advance!

**Comment by abique** [comment]
You need to install your libc development headers.

**Comment by SammDu** [comment]
Could u please tell me the exact package name (under ubuntu) that i need to install? Cuz there's just a ton with similar names and i don't know which to install...
By the way, here are all the packages i've installed that contain the Keyword "libc" dumped with "dpkg -l|grep libc" that u might find helpful:
***
    ii  klibc-utils                                       2.0.4-8ubuntu3                                              amd64        small utilities built with klibc for early boot
    ii  libc-bin                                          2.24-3ubuntu1                                               amd64        GNU C Library: Binaries
    ii  libc-dev-bin                                      2.24-3ubuntu1                                               amd64        GNU C Library: Development binaries
    ii  libc6:amd64                                       2.24-3ubuntu1                                               amd64        GNU C Library: Shared libraries
    ii  libc6:i386                                        2.24-3ubuntu1                                               i386         GNU C Library: Shared libraries
    ii  libc6-dbg:amd64                                   2.24-3ubuntu1                                               amd64        GNU C Library: detached debugging symbols
    ii  libc6-dev:amd64                                   2.24-3ubuntu1                                               amd64        GNU C Library: Development Libraries and Header Files
    ii  libc6-i386                                        2.24-3ubuntu1                                               amd64        GNU C Library: 32-bit shared libraries for AMD64
    ii  libc6-udeb                                        2.24-3                                                      amd64        GNU C Library: Shared libraries - udeb
    ii  libcaca0:amd64                                    0.99.beta19-2build2~gcc5.2                                  amd64        colour ASCII art library
    ii  libcairo-gobject2:amd64                           1.14.6-1build1                                              amd64        Cairo 2D vector graphics library (GObject library)
    ii  libcairo-perl                                     1.106-1build1                                               amd64        Perl interface to the Cairo graphics library
    ii  libcairo-script-interpreter2:amd64                1.14.6-1build1                                              amd64        Cairo 2D vector graphics library (script interpreter)
    ii  libcairo2:amd64                                   1.14.6-1build1                                              amd64        Cairo 2D vector graphics library
    ii  libcairo2:i386                                    1.14.6-1build1                                              i386         Cairo 2D vector graphics library
    ii  libcairomm-1.0-1v5:amd64                          1.12.0-1                                                    amd64        C++ wrappers for Cairo (shared libraries)
    ii  libcamd2:amd64                                    1:4.5.3-1                                                   amd64        symmetric approximate minimum degree library for sparse matrices
    ii  libcamel-1.2-59:amd64                             3.22.1-0ubuntu2                                             amd64        Evolution MIME message handling library
    ii  libcanberra-dev:amd64                             0.30-3ubuntu1                                               amd64        simple abstract interface for playing event sounds
    ii  libcanberra-gtk-common-dev                        0.30-3ubuntu1                                               all          simple abstract interface for playing event sounds
    ii  libcanberra-gtk-module:amd64                      0.30-3ubuntu1                                               amd64        translates GTK+ widgets signals to event sounds
    ii  libcanberra-gtk0:amd64                            0.30-3ubuntu1                                               amd64        GTK+ helper for playing widget event sounds with libcanberra
    ii  libcanberra-gtk3-0:amd64                          0.30-3ubuntu1                                               amd64        GTK+ 3.0 helper for playing widget event sounds with libcanberra
    ii  libcanberra-gtk3-module:amd64                     0.30-3ubuntu1                                               amd64        translates GTK3 widgets signals to event sounds
    ii  libcanberra-pulse:amd64                           0.30-3ubuntu1                                               amd64        PulseAudio backend for libcanberra
    ii  libcanberra0:amd64                                0.30-3ubuntu1                                               amd64        simple abstract interface for playing event sounds
    ii  libcap-ng0:amd64                                  0.7.7-3                                                     amd64        An alternate POSIX capabilities library
    ii  libcap2:amd64                                     1:2.25-1                                                    amd64        POSIX 1003.1e capabilities (library)
    ii  libcap2:i386                                      1:2.25-1                                                    i386         POSIX 1003.1e capabilities (library)
    ii  libcap2-bin                                       1:2.25-1                                                    amd64        POSIX 1003.1e capabilities (utilities)
    ii  libcapi20-3:amd64                                 1:3.27-1                                                    amd64        ISDN utilities - CAPI support libraries
    ii  libcapi20-3:i386                                  1:3.27-1                                                    i386         ISDN utilities - CAPI support libraries
    ii  libcaribou-common                                 0.4.21-1                                                    all          Configurable on screen keyboard with scanning mode - common files
    ii  libcaribou0:amd64                                 0.4.21-1                                                    amd64        Configurable on screen keyboard with scanning mode - library
    ii  libcc1-0:amd64                                    6.2.0-5ubuntu12                                             amd64        GCC cc1 plugin for GDB
    ii  libccolamd2:amd64                                 1:4.5.3-1                                                   amd64        constrained column approximate library for sparse matrices
    ii  libcddb2                                          1.3.2-5fakesync1                                            amd64        library to access CDDB data - runtime files
    ii  libcdio-cdda1:amd64                               0.83-4.2ubuntu1                                             amd64        library to read and control digital audio CDs
    ii  libcdio-paranoia1:amd64                           0.83-4.2ubuntu1                                             amd64        library to read digital audio CDs with error correction
    ii  libcdio13:amd64                                   0.83-4.2ubuntu1                                             amd64        library to read and control CD-ROM
    ii  libcdparanoia0:amd64                              3.10.2+debian-11                                            amd64        audio extraction tool for sampling CDs (library)
    ii  libcdparanoia0:i386                               3.10.2+debian-11                                            i386         audio extraction tool for sampling CDs (library)
    ii  libcdr-0.1-1:amd64                                0.1.3-2                                                     amd64        library for reading and converting Corel DRAW files
    ii  libcgi-fast-perl                                  1:2.10-1                                                    all          CGI subclass for work with FCGI
    ii  libcgi-pm-perl                                    4.32-1                                                      all          module for Common Gateway Interface applications
    ii  libcgmanager0:amd64                               0.41-2                                                      amd64        Central cgroup manager daemon (client library)
    ii  libchamplain-0.12-0:amd64                         0.12.14-1                                                   amd64        C library providing ClutterActor to display maps
    ii  libchamplain-gtk-0.12-0:amd64                     0.12.14-1                                                   amd64        Gtk+ widget to display maps
    ii  libcheese-gtk25:amd64                             3.22.0-1ubuntu1                                             amd64        tool to take pictures and videos from your webcam - widgets
    ii  libcheese8:amd64                                  3.22.0-1ubuntu1                                             amd64        tool to take pictures and videos from your webcam - base library
    ii  libcholmod3:amd64                                 1:4.5.3-1                                                   amd64        sparse Cholesky factorization library for sparse matrices
    ii  libchromaprint0:amd64                             1.3-1build1                                                 amd64        audio fingerprint library
    ii  libcilkrts5:amd64                                 6.2.0-5ubuntu12                                             amd64        Intel Cilk Plus language extensions (runtime)
    ii  libclass-accessor-perl                            0.34-1                                                      all          Perl module that automatically generates accessors
    ii  libclick-0.4-0:amd64                              0.4.45.1+16.10.20160916-0ubuntu1                            amd64        run-time Click package management library
    ii  libclone-perl                                     0.38-2                                                      amd64        module for recursively copying Perl datatypes
    ii  libclucene-contribs1v5:amd64                      2.3.3.4-4.2                                                 amd64        language specific text analyzers (runtime)
    ii  libclucene-core1v5:amd64                          2.3.3.4-4.2                                                 amd64        core library for full-featured text search engine (runtime)
    ii  libclutter-1.0-0:amd64                            1.26.0-2                                                    amd64        Open GL based interactive canvas library
    ii  libclutter-1.0-common                             1.26.0-2                                                    all          Open GL based interactive canvas library (common files)
    ii  libclutter-gst-3.0-0:amd64                        3.0.20-1                                                    amd64        Open GL based interactive canvas library GStreamer elements
    ii  libclutter-gtk-1.0-0:amd64                        1.8.0-1                                                     amd64        Open GL based interactive canvas library GTK+ widget
    ii  libclutter-imcontext-0.1-0:amd64                  0.1.4-3                                                     amd64        Open GL based interactive canvas library IMContext framework
    ii  libclutter-imcontext-0.1-bin                      0.1.4-3                                                     amd64        Open GL based interactive canvas library IMContext framework
    ii  libcmis-0.5-5v5                                   0.5.1+git20160603-3                                         amd64        CMIS protocol client library
    ii  libcogl-common                                    1.22.2-2                                                    all          Object oriented GL/GLES Abstraction/Utility Layer (common files)
    ii  libcogl-pango20:amd64                             1.22.2-2                                                    amd64        Object oriented GL/GLES Abstraction/Utility Layer
    ii  libcogl-path20:amd64                              1.22.2-2                                                    amd64        Object oriented GL/GLES Abstraction/Utility Layer
    ii  libcogl20:amd64                                   1.22.2-2                                                    amd64        Object oriented GL/GLES Abstraction/Utility Layer
    ii  libcolamd2:amd64                                  1:4.5.3-1                                                   amd64        column approximate minimum degree ordering library for sparse matrices
    ii  libcolord-gtk1:amd64                              0.1.26-1                                                    amd64        GTK+ convenience library for interacting with colord
    ii  libcolord2:amd64                                  1.3.2-1                                                     amd64        system service to manage device colour profiles -- runtime
    ii  libcolorhug2:amd64                                1.3.2-1                                                     amd64        library to access the ColorHug colourimeter -- runtime
    ii  libcomerr2:amd64                                  1.43.3-1                                                    amd64        common error description library
    ii  libcomerr2:i386                                   1.43.3-1                                                    i386         common error description library
    ii  libconfig++9v5:amd64                              1.5-0.2                                                     amd64        parsing/manipulation of structured configuration files (C++ binding)
    ii  libcrack2:amd64                                   2.9.2-3                                                     amd64        pro-active password checker library
    ii  libcroco3:amd64                                   0.6.11-1                                                    amd64        Cascading Style Sheet (CSS) parsing and manipulation toolkit
    ii  libcryptsetup4:amd64                              2:1.7.2-0ubuntu1                                            amd64        disk encryption support - shared library
    rc  libcryptui0a:amd64                                3.12.2-1                                                    amd64        UI library for OpenPGP prompts
    ii  libcrystalhd3:amd64                               1:0.0~git20110715.fdd2f19-11build1                          amd64        Crystal HD Video Decoder (shared library)
    ii  libcuda1-367                                      367.57-0ubuntu3                                             amd64        NVIDIA CUDA runtime library
    ii  libcue1                                           1.4.0-1                                                     amd64        CUE Sheet Parser Library
    ii  libcups2:amd64                                    2.2.0-2                                                     amd64        Common UNIX Printing System(tm) - Core library
    ii  libcups2:i386                                     2.2.0-2                                                     i386         Common UNIX Printing System(tm) - Core library
    ii  libcupscgi1:amd64                                 2.2.0-2                                                     amd64        Common UNIX Printing System(tm) - CGI library
    ii  libcupsfilters1:amd64                             1.11.4-0ubuntu2                                             amd64        OpenPrinting CUPS Filters - Shared library
    ii  libcupsimage2:amd64                               2.2.0-2                                                     amd64        Common UNIX Printing System(tm) - Raster image library
    ii  libcupsmime1:amd64                                2.2.0-2                                                     amd64        Common UNIX Printing System(tm) - MIME library
    ii  libcupsppdc1:amd64                                2.2.0-2                                                     amd64        Common UNIX Printing System(tm) - PPD manipulation library
    ii  libcurl3:amd64                                    7.50.1-1ubuntu1.1                                           amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
    ii  libcurl3-gnutls:amd64                             7.50.1-1ubuntu1.1                                           amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
    ii  libcwidget3v5:amd64                               0.5.17-4ubuntu2                                             amd64        high-level terminal interface library for C++ (runtime files)
    ii  libklibc                                          2.0.4-8ubuntu3                                              amd64        minimal libc subset for use with initramfs
    ii  liblocale-gettext-perl                            1.07-3                                                      amd64        module using libc functions for internationalization in Perl
    ii  libpthread-stubs0-dev:amd64                       0.3-4                                                       amd64        pthread stubs not provided by native libc, development files
    ii  linux-libc-dev:amd64                              4.8.0-27.29                                                 amd64        Linux Kernel Headers for development
    ii  linux-libc-dev:i386                               4.8.0-27.29                                                 i386         Linux Kernel Headers for development
***

**Comment by abique** [comment]
libc6-dev

**Comment by SammDu** [comment]
But when i search for **libc6-dev** it says that i've already installed it :/

    # aptitude search libc6-dev
    i A libc6-dev                           - GNU C Library: Development Libraries and Head

**Comment by SammDu** [comment]
do i need a i386 version though cuz i'm using a 64bit system and the "-1386" version is not installed as indicated in the package query

**Comment by abique** [comment]
Oh yes you need the headers for wineg++ while compiling for a 32bit target !

Check on google which package might provide this header, I've no idea sorry!

By the way also try to checkout https://github.com/phantom-code/airwave

**Comment by abique** [comment]
Try to install those:

gcc-c++ git cmake wine wine-devel wine-devel.i686 file file-devel libX11-devel libX11-devel.i686 qt5-devel glibc-devel.i686 glibc-devel

**Comment by SammDu** [comment]
I figured out that after i installed the **wine-devel-dev** package the first part of the issue was gone...but the second part of it still exists:

    winebuild: gcc-4.7 failed with status 1
    winegcc: winebuild failed
    Makefile:8: recipe for target 'vst-bridge-host-32.exe' failed
    make[1]: *** [vst-bridge-host-32.exe] Error 2
    make[1]: Leaving directory '/home/samm/Downloads/vst-bridge-master/host'
    Makefile:2: recipe for target 'all' failed
    make: *** [all] Error 2
***
The packages u provivded was named Fedora style...and ubuntu ones are different...so my package manager couldn't find them.
I've also tried compiling the airwave tool but a [similar issue](https://github.com/phantom-code/airwave/issues/61) appeared as well.
:/ :/ :/

**Comment by SammDu** [comment]
Have u got any ideas/time yet bro?
